name: mostro_sdk
description: Mostro SDK (FFI Plugin)
version: 0.0.1
# homepage:

environment:
  sdk: ">=3.0.0 <4.0.0"
  # sdk: ">=2.19.6 <3.0.0"
  flutter: ">=2.11.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  plugin_platform_interface: ^2.1.4
  ffi: ^2.0.2
  oxidized: ^5.3.0
  equatable: ^2.0.5

dev_dependencies:
  ffigen: ^8.0.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.3.4
  build_runner: ^2.4.4
  json_serializable: ^6.7.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
