name: mostro_sdk
description: Mostro SDK (FFI Plugin)
version: 0.0.1
# homepage:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.11.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.6
  ffi: ^2.1.0
  equatable: ^2.0.5
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  ffigen: ^9.0.1
  flutter_lints: ^2.0.1
  build_runner: ^2.4.4

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
